import os
import json

from dotenv import load_dotenv
from groq import Groq


# Load .env
load_dotenv()

# Get API key
api_key = os.getenv("GROQ_API_KEY")

if not api_key:
    raise RuntimeError("GROQ_API_KEY not found in .env")

# Create Groq client
client = Groq(api_key=api_key)


def analyze_requirement(requirement: str):

    prompt = f"""
You are the AI assistant for Student Skills Exchange.

The platform helps students:
- find teammates
- exchange skills
- learn from other students
- collaborate on projects
- find people for competitions and hackathons

Analyze the following student requirement:

"{requirement}"

Return ONLY valid JSON in this exact structure:

{{
    "purpose": "",
    "role": "",
    "skills": [],
    "experience_level": "",
    "availability": "",
    "keywords": [],
    "summary": ""
}}

Rules:
- skills must be an array.
- keywords must be an array.
- Do not invent unnecessary information.
- If something is not mentioned, use an empty string.
- Keep the summary short.
- Return ONLY JSON.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": "You extract structured information from student requirements."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.1
    )

    ai_response = response.choices[0].message.content

    try:
        return json.loads(ai_response)

    except json.JSONDecodeError:
        return {
            "error": "AI returned invalid JSON",
            "raw_response": ai_response
        }
    # ============================================================
# AI SKILL VERIFICATION
# ============================================================

def generate_skill_question(
    skill: str,
    difficulty: str = "Basic",
    previous_questions: list[str] | None = None
):

    import json
    import random
    import time

    if previous_questions is None:
        previous_questions = []


    # Remove duplicates from history
    previous_questions = list(
        dict.fromkeys(
            q.strip()
            for q in previous_questions
            if q and q.strip()
        )
    )


    # Random topic to force variety
    topic_pool = [
        "variables and data types",
        "operators",
        "conditions and if-else",
        "loops",
        "functions",
        "lists",
        "tuples",
        "dictionaries",
        "sets",
        "strings",
        "slicing",
        "exception handling",
        "object oriented programming",
        "modules",
        "input and output",
        "debugging",
        "real-world programming"
    ]


    topic = random.choice(topic_pool)


    # Random value makes every generation different
    variation_id = random.randint(
        100000,
        999999
    )


    previous_text = "\n".join(
        f"- {question}"
        for question in previous_questions
    )


    if not previous_text:
        previous_text = "NONE"


    prompt = f"""
You are an AI skill verification examiner
for Student Skills Exchange.

Generate ONE multiple-choice question to test
a student's skill in:

SKILL:
{skill}

DIFFICULTY:
{difficulty}

PREFERRED TOPIC:
{topic}

RANDOM VARIATION ID:
{variation_id}


VERY IMPORTANT:

The student may have already seen some questions.

You MUST NOT repeat any question from the
previous-question list.

You MUST NOT create a question that is merely
a reworded version of a previous question.

The new question must test a DIFFERENT concept,
scenario, code example, or application.

PREVIOUS QUESTIONS:

{previous_text}


QUESTION VARIETY RULES:

- Prefer a different concept from previous questions.
- Mix conceptual questions and code/output questions.
- Sometimes ask about real-world application.
- Sometimes ask about debugging.
- Do not always ask definition questions.
- Do not always ask output questions.
- Do not always use the same correct-answer position.
- The correct answer position must be randomly
  distributed between 0, 1, 2 and 3.
- Keep exactly 4 options.
- Only ONE option must be correct.
- The question must be appropriate for the
  requested difficulty.
- Do not mention that the question was generated by AI.
- Do not use previous questions as templates.


Return ONLY valid JSON:

{{
    "question": "",
    "options": [
        "",
        "",
        "",
        ""
    ],
    "correct_answer": 0,
    "difficulty": "{difficulty}",
    "skill": "{skill}",
    "topic": "",
    "explanation": ""
}}

RULES:

- correct_answer must be an integer from 0 to 3.
- options must contain exactly 4 strings.
- explanation must explain why the correct answer is correct.
- Return ONLY JSON.
"""


    try:
            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {
                        "role": "system",
                        "content": """
    You are a strict AI skill-test question generator.
    
    Generate exactly ONE multiple-choice question.
    
    Return ONLY valid JSON.
    Do not use markdown.
    The JSON must contain:
    question, options, correct_answer, difficulty, skill, topic, explanation.
    
    There must be exactly 4 options.
    correct_answer must be 0, 1, 2, or 3.
    Only one option can be correct.
    """
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.5,
                max_completion_tokens=700,
                response_format={
                    "type": "json_object"
                }
            )
    
            raw = (
                response.choices[0]
                .message.content
                .strip()
            )
    
            result = json.loads(raw)
    
            # Validate options
            if not isinstance(
                result.get("options"),
                list
            ):
                raise ValueError(
                    "AI did not return options."
                )
    
            if len(result["options"]) != 4:
                raise ValueError(
                    "AI must return exactly 4 options."
                )
    
            # Validate correct answer
            correct_answer = int(
                result.get("correct_answer", 0)
            )
    
            if correct_answer not in [0, 1, 2, 3]:
                raise ValueError(
                    "Invalid correct answer index."
                )
    
            result["correct_answer"] = correct_answer
            result["difficulty"] = difficulty
            result["skill"] = skill
    
            # Duplicate check
            generated_question = (
                result.get("question", "")
                .strip()
            )
    
            generated_normalized = (
                generated_question
                .lower()
                .replace("?", "")
                .replace(".", "")
                .replace("!", "")
                .strip()
            )
    
            for old_question in previous_questions:
                old_normalized = (
                    old_question
                    .lower()
                    .replace("?", "")
                    .replace(".", "")
                    .replace("!", "")
                    .strip()
                )
    
                if generated_normalized == old_normalized:
                    return {
                        "error":
                        "AI generated a duplicate question. Please retry."
                    }
    
            return result

    except Exception as e:

        # IMPORTANT:
        # Never let AI failure break the skill test.
        print(
            "GROQ AI ERROR:",
            repr(e)
        )

        # Fallback question for live demo
        fallback_questions = [
            {
                "question":
                    "Which keyword is used to define a function in Python?",
                "options": [
                    "func",
                    "def",
                    "function",
                    "define"
                ],
                "correct_answer": 1,
                "topic": "functions",
                "explanation":
                    "The def keyword is used to define a function in Python."
            },
            {
                "question":
                    "What is the output of: print(2 + 3 * 4)?",
                "options": [
                    "20",
                    "14",
                    "24",
                    "10"
                ],
                "correct_answer": 1,
                "topic": "operators",
                "explanation":
                    "Multiplication has higher precedence than addition, so 3 * 4 is 12 and 2 + 12 is 14."
            },
            {
                "question":
                    "Which data type is used to store True or False in Python?",
                "options": [
                    "int",
                    "str",
                    "bool",
                    "float"
                ],
                "correct_answer": 2,
                "topic": "data types",
                "explanation":
                    "The bool data type stores True or False values."
            },
            {
                "question":
                    "Which method adds an item to the end of a Python list?",
                "options": [
                    "add()",
                    "insertEnd()",
                    "append()",
                    "push()"
                ],
                "correct_answer": 2,
                "topic": "lists",
                "explanation":
                    "The append() method adds an item to the end of a Python list."
            },
            {
                "question":
                    "Which symbol starts a comment in Python?",
                "options": [
                    "//",
                    "#",
                    "/*",
                    "--"
                ],
                "correct_answer": 1,
                "topic": "syntax",
                "explanation":
                    "Python uses # to begin a single-line comment."
            }
        ]

        import random

        result = random.choice(
            fallback_questions
        )

        result["difficulty"] = difficulty
        result["skill"] = skill

        print(
            "Using fallback skill question."
        )

        return result


# ============================================================
# AI ANSWER EVALUATION
# ============================================================

def evaluate_skill_answer(
    skill: str,
    question: str,
    options: list,
    correct_answer: int,
    student_answer: int,
    difficulty: str
):
    """
    AI evaluates the student's answer and provides
    an explanation and performance feedback.
    """

    selected_answer = ""

    if (
        isinstance(student_answer, int)
        and 0 <= student_answer < len(options)
    ):
        selected_answer = options[student_answer]


    correct_option = ""

    if (
        isinstance(correct_answer, int)
        and 0 <= correct_answer < len(options)
    ):
        correct_option = options[correct_answer]


    prompt = f"""
You are evaluating a student's skill verification test.

Skill:
{skill}

Difficulty:
{difficulty}

Question:
{question}

Options:
{json.dumps(options)}

Correct answer:
{correct_option}

Student's answer:
{selected_answer}

Determine whether the student demonstrated understanding.

Return ONLY valid JSON:

{{
    "correct": true,
    "score": 0,
    "explanation": "",
    "skill_level_signal": "",
    "feedback": ""
}}

Rules:

- correct must be true or false.
- score must be between 0 and 100.
- explanation must be short.
- skill_level_signal must be one of:
  "basic",
  "intermediate",
  "advanced"
- feedback should be useful to the student.
- Return ONLY JSON.
"""

    response = client.chat.completions.create(

        model="llama-3.3-70b-versatile",

        messages=[
            {
                "role": "system",
                "content":
                "You are an AI skill assessment evaluator."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],

        temperature=0.2
    )

    ai_response = response.choices[0].message.content.strip()

    try:

        if ai_response.startswith("```"):
            ai_response = (
                ai_response
                .replace("```json", "")
                .replace("```", "")
                .strip()
            )

        return json.loads(ai_response)

    except json.JSONDecodeError:

        return {
            "error": "AI returned invalid JSON",
            "raw_response": ai_response
        }


# ============================================================
# FINAL AI VERIFICATION
# ============================================================

def calculate_skill_verification(
    skill: str,
    answers: list
):
    """
    Final AI-powered skill verification.

    The per-question scores are calculated during the test.
    Groq analyzes those scores and determines:
    - overall score
    - knowledge
    - problem solving
    - practical ability
    - skill level
    - AI confidence
    """

    if not answers:
        return {
            "error": "No answers were provided."
        }

    # --------------------------------------------------------
    # Calculate a reliable baseline from question evaluations
    # --------------------------------------------------------

    valid_scores = []

    for answer in answers:

        try:
            score = float(answer.get("score", 0))

            score = max(
                0,
                min(100, score)
            )

            valid_scores.append(score)

        except (TypeError, ValueError):
            continue


    if not valid_scores:
        return {
            "error": "No valid evaluation scores were found."
        }


    baseline_score = round(
        sum(valid_scores) / len(valid_scores)
    )


    correct_count = sum(
        1
        for answer in answers
        if answer.get("correct") is True
    )


    total_questions = len(answers)


    performance_summary = {
        "total_questions": total_questions,
        "correct_answers": correct_count,
        "question_scores": valid_scores,
        "baseline_score": baseline_score,
        "answers": answers
    }


    # --------------------------------------------------------
    # Ask Groq for final AI assessment
    # --------------------------------------------------------

    prompt = f"""
You are the final AI skill evaluator for
Student Skills Exchange.

The student claims they can teach:

SKILL:
{skill}

The student completed an adaptive AI verification test.

Here is the COMPLETE performance data:

{json.dumps(performance_summary, indent=2)}

IMPORTANT SCORING RULES:

1. The per-question "score" values are already calculated
   by the AI during the individual answer evaluations.

2. Use these scores as the primary evidence.

3. The baseline score is:
{baseline_score}

4. The final overall_score MUST normally be close to the
   baseline score.

5. NEVER return 0 for overall_score if valid question scores
   are available.

6. Only return 0 if there are genuinely no valid answers.

7. Do not arbitrarily give the student a perfect score.

8. Evaluate the student's actual performance.

9. Knowledge score should represent conceptual understanding.

10. Problem solving score should represent ability to apply
    knowledge and solve problems.

11. Practical score should represent real-world application.

12. Determine the level:

    Basic:
    approximately 0-59

    Intermediate:
    approximately 60-79

    Advanced:
    approximately 80-100

13. "verified" should be true when the student demonstrates
    sufficient ability to teach the claimed skill.

14. AI confidence should represent how confident you are
    in the assessment based on the available evidence.

Return ONLY valid JSON in exactly this structure:

{{
    "skill": "{skill}",
    "overall_score": 0,
    "knowledge_score": 0,
    "problem_solving_score": 0,
    "practical_score": 0,
    "level": "",
    "verified": false,
    "ai_confidence": 0,
    "strengths": [],
    "weaknesses": [],
    "summary": ""
}}

Rules:

- All scores must be integers from 0 to 100.
- overall_score should be based primarily on the
  question_scores.
- Do not return 0 when valid scores exist.
- level must be exactly:
  "Basic", "Intermediate", or "Advanced".
- strengths must be an array.
- weaknesses must be an array.
- summary must be short.
- Return ONLY JSON.
"""


    response = client.chat.completions.create(

        model="llama-3.3-70b-versatile",

        messages=[

            {
                "role": "system",
                "content":
                "You are a fair, rigorous AI skill certification evaluator."
            },

            {
                "role": "user",
                "content": prompt
            }

        ],

        temperature=0.1

    )


    ai_response = (
        response
        .choices[0]
        .message
        .content
        .strip()
    )


    try:

        # Remove markdown fences if Groq adds them

        if ai_response.startswith("```"):

            ai_response = (
                ai_response
                .replace("```json", "")
                .replace("```", "")
                .strip()
            )


        result = json.loads(
            ai_response
        )


        # ----------------------------------------------------
        # Safety normalization
        # ----------------------------------------------------

        def safe_score(value, fallback):

            try:

                value = int(
                    round(float(value))
                )

                if value < 0:
                    return 0

                if value > 100:
                    return 100

                return value

            except (
                TypeError,
                ValueError
            ):

                return fallback


        result["overall_score"] = safe_score(
            result.get("overall_score"),
            baseline_score
        )


        result["knowledge_score"] = safe_score(
            result.get("knowledge_score"),
            baseline_score
        )


        result["problem_solving_score"] = safe_score(
            result.get("problem_solving_score"),
            baseline_score
        )


        result["practical_score"] = safe_score(
            result.get("practical_score"),
            baseline_score
        )


        result["ai_confidence"] = safe_score(
            result.get("ai_confidence"),
            85
        )


        # ----------------------------------------------------
        # Prevent impossible 0 score
        # ----------------------------------------------------

        if baseline_score > 0:

            if result["overall_score"] == 0:

                result["overall_score"] = baseline_score


        # ----------------------------------------------------
        # Ensure valid level
        # ----------------------------------------------------

        level = result.get(
            "level",
            ""
        )


        if level not in [
            "Basic",
            "Intermediate",
            "Advanced"
        ]:

            if result["overall_score"] >= 80:

                level = "Advanced"

            elif result["overall_score"] >= 60:

                level = "Intermediate"

            else:

                level = "Basic"


        result["level"] = level


        # ----------------------------------------------------
        # Verification decision
        # ----------------------------------------------------

        result["verified"] = (
            result["overall_score"] >= 70
        )


        return result


    except json.JSONDecodeError:

        # ----------------------------------------------------
        # Fallback if Groq returns malformed JSON
        # ----------------------------------------------------

        if baseline_score >= 80:

            level = "Advanced"

        elif baseline_score >= 60:

            level = "Intermediate"

        else:

            level = "Basic"


        return {

            "skill": skill,

            "overall_score":
                baseline_score,

            "knowledge_score":
                baseline_score,

            "problem_solving_score":
                baseline_score,

            "practical_score":
                baseline_score,

            "level":
                level,

            "verified":
                baseline_score >= 70,

            "ai_confidence":
                80,

            "strengths": [],

            "weaknesses": [],

            "summary":
                "Assessment completed using AI-evaluated question performance.",

            "raw_response":
                ai_response

        }